### PR TITLE
add crespo4g to blandroid

### PR DESCRIPTION
**Pull request by jcs**

### CODE REVIEW

**Comment by koush** [comment]
Think you can move your developer entry over to ROM Share? It's a lot easier to use, and less maintenance for both of us. It will let you use your current developer manifest ,should only take a minute or two to set up.

Koush

**Comment by koush** [comment]
Oh, realized a link would help
http://romshare.deployfu.com

**Comment by jcs** [comment]
ok, i've added it to that site.

**Comment by koush** [comment]
Great, everything should be set then.

**Pull request closed without merging**
