### PR TITLE
compile new recovery

### PR DESCRIPTION
**Pull request by arif-ali**
compile new recovery for leo please

thanks

### CODE REVIEW

**Comment by arif-ali** [comment]
Hey koush,

The values have been added, How do we go about actually creating the image. it's not on the server. Or is there a way to specify our own URLs.

regards,
Arif

**Comment by koush** [comment]
I built it for you last night. CWR recoveries in ROM Manager must all be built by me.

**Comment by arif-ali** [comment]
I appreciate that, thanks

FYI, they are on 

http://mirrorbrain.cyanogenmod.com/cm/recoveries/

but not on the link below. and the new devices.js is pointing to link below

http://mirror.sea.tdrevolution.net/cm/recoveries/

any ideas on that, and everyone now sees the new version, but no file

**Comment by koush** [comment]
oh, right. The mirror service is down. Give me a bit. I need to fix up the publishing scripts.

**Comment by arif-ali** [comment]
let me know when it is fixed, so that I can let the users know

**Pull request closed without merging**
