### PR TITLE
Adding Devices to LSR

### PR DESCRIPTION
**Pull request by jbroom**
Adding Droid 2 World and Droid Inc 2

### CODE REVIEW

**Comment by koush** [comment]
Hey! Mind switching to ROM Share? http://romshare.deployfu.com

I'm trying to get developers moved over to that. You can still use manual manifests on there as you are now. Let me know when you've added yourself there.

**Comment by jbroom** [comment]
I've added myself to that... does RM automatically add new devices as i change my manifest now?

**Comment by koush** [comment]
Yes. It autochecks periodically. Don't need to send pull requests anymore. Let me remove your old RM section and merge up your new one now.

**Comment by koush** [comment]
All done, let me know if something went wrong.

**Pull request closed without merging**
