### PR TITLE
Add some newly supported devices and fix some others

### PR DESCRIPTION
**Pull request by n-i-x**
Koush: vivo ROM will be uploaded by Sunday.. trying to launch in ROM Manager immediately once we post on the site.

Thanks!

### CODE REVIEW

**Comment by koush** [comment]
Wow! Nice job!

**Comment by koush** [comment]
showcasemtd and mesmerizemtd are not supported by ROM Manager. How can I build recoveries for those?

**Comment by n-i-x** [comment]
You already have the recoveries built! The fascinatemtd, showcasemtd, and mesmerizemtd all use the fascinate recovery. They are all sch-i500 devices with a different carrier label on the front :)

If you need someone to test a beta version of ROM Manager or something I can arrange that. Also, if you do fix the *mtd device support in ROM Manager a ton of devs and users will love you long time!

**Comment by koush** [comment]
Weird. They're MTD devices though, how does the fascinate recovery even work?

**Comment by koush** [comment]
It's bml and rfs.

**Pull request merged**
