### PR TITLE
Manifest location has changed again, please update.

### PR DESCRIPTION
**Pull request by sonofskywalker3**

### CODE REVIEW

**Comment by pcmac77** [comment]
Looks like this was done in another commit : https://github.com/koush/ROMManagerManifest/commit/db0407428a738b02fb09921686e1fd35ada8ed1b and merged by koush.  Was it a duplicate?

**Comment by sonofskywalker3** [comment]
looks like he merged it but didn't close it, however it doesn't appear to be
pulling the manifest from the new location yet in rom manager

**Comment by sonofskywalker3** [comment]
I changed the manifest at the new location but the changes aren't in rom
manager.

**Comment by pcmac77** [comment]
have you tried clearing your download cache in rommanager?

**Comment by sonofskywalker3** [comment]
I have, but it's still pulling from the old location. the only difference is
the new one has the "~" in front of "sonofskywalker3"

**Comment by sonofskywalker3** [comment]
Any ideas? It's still pulling my old manifest....

**Comment by pcmac77** [comment]
please stand by...

**Comment by pcmac77** [comment]
Okay, it should be good now.

**Comment by sonofskywalker3** [comment]
I'm in business. Much thanks.
On Mar 16, 2011 7:40 PM, "pcmac77" <
reply@reply.github.com>
wrote:

**Pull request merged**
