### PR TITLE
Add LeeDrOiD to Rom Manager

### PR DESCRIPTION
**Pull request by LeeDroid-**
I have also removed the current entry in manifests.js linked to romshare.deployfu.com

### CODE REVIEW

**Comment by koush** [comment]
The proper way to do this would be to disable your account on ROM share, and add yourself to manual_manifests.
Log into ROM Share, and disable it.

**Comment by LeeDroid-** [comment]
Acccount disabled, do you need me to re-submit this request?

**Comment by LeeDroid-** [comment]
Hi koush

Is it possible to add an ext4 hook for wiping data and cache in RM?
On Jun 27, 2011 6:29 AM, "koush" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
ext4 hook? what do you mean?

**Comment by LeeDroid-** [comment]
When selecting full wipe it auto formats to ext3 on all partitions, the only
way users can format to ext4 is use my additional full wipe zip, most DHD
custom ROMs are running on ext4 atm, would be a fantastic addition to RM and
cwm to have a full wipe sub menu ;)
On Jun 27, 2011 6:03 PM, "koush" <
reply@reply.github.com>
wrote:

**Comment by ghost** [comment]
atm when you build a CW recovery the sd-ext will get formated to what ever is set in the recovery.fstab.

But as i told you koush some time ago ,when set to ext4 in fstab and formatted with the ext4_utils that it gets buggy.
Maybe a separated format sd-ext to ext3 and to ext4 (maybe under Advanced/Partition SDcard) would fix most of the demands, in the end we can simply use tune2fs to do everything in there.

**Comment by LeeDroid-** [comment]
Not talking about ext squire, we have the internal emmc formatted as ext4
across all partitions, /system /data & /cache, currently using a seperate
updater script to do so
On Jun 27, 2011 6:49 PM, "roalex" <
reply@reply.github.com>
wrote:

**Pull request merged**
