### PR TITLE
jamezelle update devices in manifest

### PR DESCRIPTION
**Pull request by ghost**
thanks

### CODE REVIEW

**Comment by koush** [comment]
Also, lets move this into free if it isn't already

**Comment by ghost** [comment]
havent added an icon do i add that in the developer manifest or the main one?

**Comment by koush** [comment]
it's in the main manifest, this one that you submitted a pull for. check the other icons out!

**Comment by ghost** [comment]
ok I'll create a separate pull request for the icon if needed, or if you want to add it, here is the link.

http://jamezelle.com/RomManagerManifest/jamezelle-RMicon.jpg

**Comment by DrMacinyasha** [comment]
Can you make the icon 128x128?

**Comment by ghost** [comment]
ok will do

**Pull request closed without merging**
