### PR TITLE
added Info for Dev: RealPariah to manual_manifest.js and verified entire 

### PR DESCRIPTION
**Pull request by RealPariah**
added Info for Dev: RealPariah to manual_manifest.js and verified entire file with JSONlint

My ROM Site:Http://www.ambrosialpariah.com/ambrosialcm7

First time I am attempting this and using git, but verified entire manual_manifest with the JSONLint Utility

Email: CliqXT@ambrosialpariah.com

Thank you for an awesome product and your time and consideration!

### CODE REVIEW

**Comment by koush** [comment]
You messed with the other CyanogenMod entries. Can you redo this commit please?

**Comment by RealPariah** [comment]
On 7/19/2011 7:38 PM, koush wrote:

> You messed with the other CyanogenMod entries. Can you redo this commit please?
> 
> Koush,
> Wow, all I did was copy off the my brain hurts site, then filled in my 
> values and all.  I never even touched anything else.  I will try again.  
> I am sorry I am new to git.  I am a comp guru, but have not had to get 
> in to the coding side of things, but I really like the portability and 
> customization Android is capable of so I started to customize a ROM, 
> giot Turl's blessing and here I am so please bear with me I am trying my 
> best :-)  Thank you for the heands up and as I said I will give it 
> another shot.

Oh, I feel you on the work part, but I did also put up not only the 
manifest needed on my site, but the editted entry as standalone .js 
[both linked below [if I mess up again or something and you would not 
mind helping me out that would be awesome].  If there is any grunt work 
I could do in return or if I can offer some of my server space and 
bandwidth or something let me know.

http://www.ambrosialpariah.com/ambrosialcm7/files/rom.man/1.js [the 
entry I created to paste in to manual_manifest [tried to get it all set 
before editing the manifests file]

http://www.ambrosialpariah.com/ambrosialcm7/files/rom.man/acm.js [this 
is the manifest that is to remain on my server]

both of those should load as text per the htaccess [which will change 
when ROM Manager is all set so they can not be read that easily] [tested 
with FF 6 Beta]

**Comment by RealPariah** [comment]
On 7/19/2011 7:38 PM, koush wrote:

> You messed with the other CyanogenMod entries. Can you redo this commit please?
> 
> Oh and I am sorry to double mail, but if you pull my github account I 
> have also listed both manifests there til this gets set so if that helps.

git://github.com/RealPariah/AmbrosialCM7-ROM.Manager.git

**Comment by RealPariah** [comment]
WOW, looking at that diff I do not know how all THAT happened.  I must have copied and pasted and something hiccuped between text editor JSON Lint and git.  I am VERY Sorry that was a mess.  The second attempt I have put in for def should be good to go I reviewed diff and it is only the 11 lines pertaining to my info that are definitely changed.

**Pull request closed without merging**
