### PR TITLE
Change in the manifest URL for the Ideos Dev Team

### PR DESCRIPTION
**Pull request by LalitMaganti**
Sorry for asking for another change but SourceForge has become too unreliable so we switched it to GitHub.

Thanks in advance.

### CODE REVIEW

**Comment by koush** [comment]
Mind removing your manifest altogether in a pull request? Then add yourself via http://romshare.deployfu.com

That is a much easier way to manage it for both of us.

**Comment by LalitMaganti** [comment]
Done as you asked

**Comment by koush** [comment]
cool. looks like you did not change your developer name yet on rom share. let me know when you do.

**Comment by LalitMaganti** [comment]
Have changed the developer name. Thanks for the ROM share tip.

**Pull request merged**
