### PR TITLE
two more devices, p1l and p1n

### PR DESCRIPTION
**Pull request by chirayudesai**
Might need to think of better names, they are just a GSM tab with a different kernel

### CODE REVIEW

**Comment by koush** [comment]
Build failed:

``` bash

Lion:ics$ make -j8 recoveryimage
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=4.0.4
TARGET_PRODUCT=cm_p1l
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
HOST_ARCH=x86
HOST_OS=darwin
HOST_BUILD_TYPE=release
BUILD_ID=IMM76L
============================================
system/core/toolbox/Android.mk:98: warning: overriding commands for target `out/target/product/p1l/system/bin/lsof'
build/core/base_rules.mk:523: warning: ignoring old commands for target `out/target/product/p1l/system/bin/lsof'
build/core/Makefile:36: warning: overriding commands for target `out/target/product/p1l/system/etc/mkshrc'
build/core/base_rules.mk:523: warning: ignoring old commands for target `out/target/product/p1l/system/etc/mkshrc'
build/core/Makefile:36: warning: overriding commands for target `out/target/product/p1l/system/bin/rild'
build/core/base_rules.mk:523: warning: ignoring old commands for target `out/target/product/p1l/system/bin/rild'
build/core/Makefile:36: warning: overriding commands for target `out/target/product/p1l/system/lib/egl/libGLES_android.so'
build/core/base_rules.mk:523: warning: ignoring old commands for target `out/target/product/p1l/system/lib/egl/libGLES_android.so'
No private recovery resources for TARGET_DEVICE p1l
build/core/tasks/kernel.mk:118: warning: overriding commands for target `TARGET_KERNEL_BINARIES'
device/samsung/p1-common/shbootimg.mk:26: warning: ignoring old commands for target `TARGET_KERNEL_BINARIES'
make -C kernel/samsung/p1 O=/Volumes/Data/ics/out/target/product/p1l/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=" /Volumes/Data/ics/prebuilt/darwin-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-" cyanogenmod_p1l_defconfig
target Symbolic: recovery (out/target/product/p1l/symbols/system/bin/recovery)
make: Circular out/target/product/p1l/boot.img <- out/target/product/p1l/kernel dependency dropped.
  GEN     /Volumes/Data/ics/out/target/product/p1l/obj/KERNEL_OBJ/Makefile
target Symbolic: static_busybox (out/target/product/p1l/symbols/utilities/busybox)
zcat out/target/product/p1l/ramdisk.img > out/target/product/p1l/ramdisk.cpio
zcat: out/target/product/p1l/ramdisk.img.Z: No such file or directory
make: *** [out/target/product/p1l/ramdisk.cpio] Error 1
make: *** Deleting file `out/target/product/p1l/ramdisk.cpio'
make: *** Waiting for unfinished jobs....
drivers/cpufreq/Kconfig:140:warning: defaults for choice values not supported
drivers/cpufreq/Kconfig:146:warning: defaults for choice values not supported
#
# configuration written to .config
#
```

**Comment by chirayudesai** [comment]
seems like a darwin derp, just ran a recovery build and it went fine.

**Comment by chirayudesai** [comment]
bump, this was fixed, wasn't it?

**Comment by koush** [comment]
Let me check. I may have fixed it and forgotten./

**Pull request closed without merging**
