### PR TITLE
Update manifest/vivow.js

### PR DESCRIPTION
**Pull request by DhE17roms**
Im developing roms for the incredible 2 now. Just added my dev info to the file and already updated my manifest file. Let me know if you need anything else.

### CODE REVIEW

**Comment by koush** [comment]
Err, you don't actually edit this  file yourself. I'm trying to stop using this github method. Please sign up on the new developer site:

http://developer.clockworkmod.com

Provide it your current manifest file. It should only take you a few minutes to set up. All the device support is done automatically; it will detect what ROMs you provide.

**Comment by koush** [comment]
Please let me know when you have signed up on that site.

**Comment by DhE17roms** [comment]
One quick question about that site. Im signed up, but do I give it my personal manifest or the manifest with my roms listed out? Also, do I need to upload my roms to that site for it to function properly? Just makin sure I do it right and cause as small a headache as possible for you.

**Comment by DhE17roms** [comment]
Alright, all signed up. Used the manifest that lists the roms. If thats wrong let me know and I will update it. Thanks for the great work.

**Comment by koush** [comment]
Great, I've removed your old entry, and your new entry is now on the developer portal. Thanks!

**Pull request closed without merging**
