### PR TITLE
Add Leo to CyanogenMod

### PR DESCRIPTION
**Pull request by charansingh**
Fixes CyanogenMod not showing on Leo

### CODE REVIEW

**Comment by ctso** [comment]
This device is not officially supported.

**Comment by charansingh** [comment]
I had asked cyanogen and he agreed with having it on Rom Manager, Provided it is hosted by me and not CyanogenMod and there is a vendor for it in CyanogenMod

**Comment by koush** [comment]
Please submit a new rom like this:
http://www.koushikdutta.com/2010/03/rom-manager-and-third-party-roms.html

This is not a official CM release from what I understand.

**Comment by charansingh** [comment]
I talked to cyanogen about it and said it was ok to be on Rom Manager under CyanogenMod name as long as it was hosted by me and not by cyanogenmod servers.

**Comment by koush** [comment]
Ok, that's fine. Please just create a new entry called "CyanogenMod" with developer "charansingh" that you host and manage yourself, since we are apparently not hosting and managing it.

**Comment by koush** [comment]
That way you don't have to send continual pull requests to update your list. I'll be removing leo from our manifest by the end of day today, so get started on making your own :)

**Comment by ctso** [comment]
Kind of unrelated, but I'm going to start generating the 'official' CM manifest automagically to avoid stuff like this in the future.  If it isn't hosted on download.cyanogenmod.com, it is not CyanogenMod and does not belong in the manifest.

**Comment by koush** [comment]
I agree. @cyanogen wants the build bot to build all official releases anyways. When individuals build, they always fuck something up. This way, we can either get it all right in one go (or fuck it up en masse, kekekeke)

**Pull request closed without merging**
