### PR TITLE
the VM670 uses the aosp ROM.  I'm not sure why it's listed under the mani

### PR DESCRIPTION
**Pull request by ghost**
the VM670 uses the aosp ROM.  I'm not sure why it's listed under the manifest/thunderg.js
Unless that phone uses it too it should be removed from that manifest, but put here regardless.
Proof:
open ROM Manager
select Optimus One as your device, go to downloads section/aosp and look at the naming of the aosp builds.  
 They're all for VM670 aka Optimus V.
select Optimus V as your device and the aosp builds are not present

  further proof here where rom used to be available until they ported to ROM Manager http://romrepo.info/wiki/index.php?title=LG_Optimus_V
discussions on how this model mixup is confusing people (it gets pretty hateful about ROM Manager.   may want to read some of the pages just to see what the gripes are.  Specifically this and the 3.2.0.0 recovery is screwing up flashes with build.prop errors.)
http://forum.xda-developers.com/showthread.php?t=962862&page=204

### CODE REVIEW

**Comment by koush** [comment]
This isn't how it works. aosp is hosting their stuff on rom share, and THEY set their device as thunderg. THEY need to fx by reuploading for Optimus One (vm670) as well.

| 185 |         322 | aospCMod-VM670-20110523          | thunderg | aospCMod-VM670-20110523-signed.zip | AOSP 2.3.4 / CM7+ (Gingerbread) |          | aospCMod-VM670-20110523 |       1 | NULL            |
| 187 |         322 | aospCMod-HEROC-20110523          | heroc    | aospCMod-HEROC-20110523-signed.zip | AOSP 2.3.4 / CM7+ (Gingerbread) |          | aospCMod-HEROC-20110523 |       1 | NULL            |
| 213 |         322 | aospCMod-VM670-20110531          | thunderg | aospCMod-VM670-20110531-signed.zip | AOSP 2.3.4 / CM7+ (Gingerbread) | 0531     | aospCMod-VM670-20110531 |       1 | aospmod         |
| 224 |         322 | aospCMod-VM670-20110601          | thunderg | aospCMod-VM670-20110601-signed.zip | AOSP 2.3.4 / CM7+ (Gingerbread) | 20110601 | aospCMod-VM670-20110601 |       0 | aospmod         |
| 225 |         322 | aospCMod-VM670-20110601-MMSFIXED | thunderg | aospCMod-VM670-20110601-signed.zip | AOSP 2.3.4 / CM7+ (Gingerbread) | 20110601 | aospCMod-VM670-20110601 |       1 | aospmod         |

**Comment by koush** [comment]
The pull request won't work. Those files are generated automatically by ROM share. http://romshare.deployfu.com

**Comment by ghost** [comment]
thanks.  I kinda figured the ROM maintainer makes those changes

**Comment by ajones23** [comment]
I've found out that CWM 3.0.2.4 works well with 20110601.

**Comment by ghost** [comment]
I've been using Clockwork Recovery 3.1.0.1 from RomRepo (http://romrepo.info/wiki/index.php?title=LG_Optimus_V) as it was the last one posted before they started making their ROM available on ROM Manager, however this git post is not talking about the Clockwork Recovery.  This git ticket is talking about the fact that you have to select Optimus One in ROM Manager to download Optimus V ROMs when there is now an Optimus V option in ROM Manager where the Optimus V ROMs should be published.

**Pull request closed without merging**
