### PR TITLE
Change n_i_x repo to MIUI.us

### PR DESCRIPTION
**Pull request by n-i-x**
Updated the proper file this time.

### CODE REVIEW

**Comment by koush** [comment]
You only have support for passion at the moment. Please open another pull request once you actually support all these devices.

**Comment by koush** [comment]
Judging from your current content I mean:
http://roms.miui.us/manifest/rommanager.js

**Comment by n-i-x** [comment]
OK no problem.. the ROM's will be uploaded by the end of the day. Since we do releases on Friday's, I didn't want to have old ROM's in RM.

Was hoping to have RM ready to go for when the developers are done updating, translating and uploading their rom's. You can see from http://miui.us that we do support all these devices.

**Comment by koush** [comment]
Ok, I'll let you publish them all now. Please get them up ASAP.

**Comment by n-i-x** [comment]
Thank you very much!

**Pull request merged**
