### PR TITLE
Add developer ZaReason

### PR DESCRIPTION
**Pull request by zareason**

### CODE REVIEW

**Comment by koush** [comment]
Hey, this isn't used anymore.

Please sign up at http://developer.clockworkmod.com

**Comment by zareason** [comment]
Did that, but my rom isn't showing up on the download list. Can you check my settings for DeveloperID=zareason?

**Comment by koush** [comment]
Ok, taking a look.

**Comment by koush** [comment]
I can see it here, but it won't show up in ROM Manager:

http://www.clockworkmod.com/rommanager/developers/MID970?name=AT%26T%20Nitro%20HD%20%2F%20LGE%20P930

It isn't ROM manager visible, because I do not recognize the "MID970" device. What is that? Your "device" will need to match the device name that ROM Manager uses to identify devices. This is usually ro.product.device.

**Comment by zareason** [comment]
These are new devices we are working on. What is the preferred way to get new devices added to ROM Manager?

ro.product.device=crane-evb

**Comment by zareason** [comment]
I updated our manifest and now the ROM is showing up. Thanks.

**Comment by koush** [comment]
Great. Is there a third party build recovery for that device or something?

**Comment by zareason** [comment]
We're putting CWM Recovery on it.

**Pull request closed without merging**
