### PR TITLE
Remove LG Optimus V support

### PR DESCRIPTION
**Pull request by tvall43**
The recovery rom manager flashes is useless on newer devices. No rom developers officially support rom manager. Everything in it is old, unsupported, and uploaded by people other than the devs.
Doing this will finally get rid of the annoying posts by noobs who "brick" their device by installing the recovery this app flashes (which has a older kernel that doesn't support the newer displays found in the current version of this phone).

### CODE REVIEW

**Comment by rukin5197** [comment]
I second this commit.

**Comment by koush** [comment]
Why not just provide me with a new kernel?

**Comment by tvall43** [comment]
https://github.com/mrg666/android_kernel_thunderc/downloads
On Aug 3, 2012 10:04 PM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
Please test:

http://download.clockworkmod.com/recoveries/recovery-clockwork-6.0.1.1-thunderc.img

**Comment by tvall43** [comment]
didn't work for me or another optimus v user.
http://forums.androidcentral.com/showthread.php?p=2043400
Hung at the boot logo for me
On Aug 4, 2012 2:59 AM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
Is there a working recovery image that I can use? Maybe the kernel I downloaded from that link is jacked up.

**Comment by koush** [comment]
Do the different devices in the thunderc line all use the same recovery image? Or are they using separate images?
LS670
LW690
MS690
VM670
VS660

**Comment by sellers86** [comment]
kernel is fine, its used on the mirage rom. but here is a working recovery for the VM670. they are different recovery images. http://www.mediafire.com/?vzc5k8taj9smmll  this will fix black screens. a link to a buildable git for the VM670 would be github.com/BobZhome/android_device_lge_thunderc   thanks.

**Comment by koush** [comment]
So, I really need to build 5 recovery images?

**Comment by sellers86** [comment]
If you want you can, I can probably build some of them. The VM670 and LS670 should be able to use the same recovery as long as the new screen driver is fixed, but the home and menu keys will be swapped. I can search for links for pre-existing working recoveries if you want.

**Comment by koush** [comment]
Can you check ro.product.device in the build.prop on your ROM?

**Comment by koush** [comment]
adb shell  getprop ro.product.device

**Comment by sellers86** [comment]
its thunderc, but thats just the board. there are differences to each phone.

**Comment by sellers86** [comment]
such as key switches and other things. especially the 660 and 690's. pretty sure there are pretty big differences there

**Comment by sellers86** [comment]
also, on ICS roms it is VM670.

**Comment by playfulgod** [comment]
The LW690 & MS690 can use the same one, but they are different from all the others. If you recall thats why we used a diff identifier for those 2 back when I first ported them. They also are the Cricket and MetroPCS versions. Both are EOL afiak too.

**Comment by sellers86** [comment]
thanks for the clarification.

**Comment by koush** [comment]
So, ro.product.device is thunderc on gb and VM670 on ics?

What is ro.product.board?

**Comment by sellers86** [comment]
yeah not sure why. Im restoring to a stock backup right now to see which is right.

**Comment by tvall43** [comment]
i personally think it would be easier to just remove support from rom manager. most rom devs encourage users to use one of the recoveries our devs built, so most users end up never using rom manager after the initial recovery flash (if they are lucky enough to have that work)

**Comment by sellers86** [comment]
on stock: ro.product.device=thunderc
ro.product.board=thunderc

this is how it should be. not sure why its different on ics.. I may ask tdm about that

**Comment by ProjectOpenCannibal** [comment]
I agree with tvall. There's also the other issue that stock CWM recoveries seem to corrupt nandroid backups, at least on {LS,VM}670. I get around that by using a binary mkyaffs2img rather than the built-in function (zefie originally noticed this when he created Xionia CWMA for LS670 and VM670), so perhaps removing support for it from ROM Manager completely would be best in this case.

It would also decrease the amount of headaches for you, Koush.

**Comment by koush** [comment]
So, exactly which devices does this recovery _currently_ work on without fail?

Since there are apparently 5 variants, the issue may just be due to mislabeling.

**Comment by IngCr3at1on** [comment]
OK; had a little bit of a discussion on this one and I'm sorry to say the short answer to your question is really none (allow me to explain my reasoning):

The current recovery image on ROM Manager (labeled for the VM670) has the potential to work on both the VM670 and the LS670...
As it stands it does work on some VM670 devices depending on the screen (kernel related/simple fix) but I don't think it works with any of the LS670 screens (always booting to a blank screen and what people assume to be a brick).

If you use the same kernel for both the LS670 and the VM670 I believe there is an issue with the home and menu buttons being reversed.

Lastly assuming you get around those relatively simple issues (I'm sure you will) there's what Drew mentioned about the internal yaff2fs support intermittently causing corrupt backups (as he mentioned this can be resolved by using CLI and a binary of mkyaffs2img).

**Comment by koush** [comment]
@IngCr3at1on The yaffs2 stuff has been fixed most likely since v3.x. The issue hasn't been reported on any recent builds.

So, in addition to there being 5 hardware versions, the versions it does work on (LS670 VM670), have shipped with new screens, which require new drivers. This seems similar to the issue I ran into with Nexus One (which shipped OLED screens, then a year later shipped LED screens which required new drivers).

I'm not too concerned with home/menu being reversed in recovery. Not that huge a deal.

If you have the VM670, please test this:
http://download.clockworkmod.com/recoveries/recovery-clockwork-6.0.1.1-vm670.img

**Comment by IngCr3at1on** [comment]
@koush That's good to hear; always happy to be corrected in those matters. Otherwise yes that about sums it up and no I don't think anyone is concerned about the buttons being reversed just thought it should be known.

**Comment by ProjectOpenCannibal** [comment]
@koush that's interesting. I'll need to do some further testing to confirm this, but when I originally started building CWM for LS670 (based on CWM 5.0.2.7) I could swear that I had experienced a few corrupted backups.

Again it'll need some further investigating on my end.

**Comment by koush** [comment]
@drewwalton19216801 I believe the issue you are referring to may have been due to mkyaffs2image being called internally. Something may not be properly being reset between subsequent calls to the function.
I fixed (work around really, similar to what you guys are doing) this in jellybean by calling the binary:

https://github.com/CyanogenMod/android_bootable_recovery/blob/jellybean/nandroid.c#L110

However, I did notice the fix is not in ics. I'll need to backport that.

**Comment by ProjectOpenCannibal** [comment]
@koush Do you think that would be an easy thing to backport to GB?

**Comment by koush** [comment]
@drewwalton19216801 Yeah, but I don't build off GB anymore. Building an ics or jb recovery will also work on gb devices.

**Comment by ProjectOpenCannibal** [comment]
@koush This is true, however I've forward-ported Amend support to CWM 5.0.2.7 because we still have a TON of Froyo-based ROMs that use Amend and an older version of nandroid was merged in as a result. The thought of re-doing everything based off ICS or JB CWM honestly scares me a bit, and we (IngCr3at1on and I) have certainly made a TON of changes.

BTW, the Amend support was a big giant PITA (naturally).

Afterthought: I am in no way saying that you should backport it to GB, merely voicing my afraid-ness of the thought of re-merging everything we've done so far :P

That said, the older version of nandroid we've merged in as a result of the Amend support patches seems to not even support non-yaffs2 devices. Do you think there would be a (hopefully easy) way for me to back-port the non-yaffs2 support?

**Comment by playfulgod** [comment]
been easier to update all the roms to edify lol

**Comment by koush** [comment]
any word on whether that linked recovery above works? http://download.clockworkmod.com/recoveries/recovery-clockwork-6.0.1.1-vm670.img

**Comment by sellers86** [comment]
Ill try it in a bit, even though switching corrupts all of my current backups.... ill let you know how it works.

**Comment by sellers86** [comment]
now your missing the old screen drivers.. it functions, but the old screens will see a blank recovery. You need to have the drivers that were in the old rom manager recovery and the new drivers in there.

**Comment by koush** [comment]
Both drivers aren't compiled into the kernel? That's how the Nexus One does it.

**Comment by sellers86** [comment]
What kernel did you use? it should be built in. It couldve been something else, but the recovery worked I just had a blank screen. I have the old optimus v screen. 

we also have a .35 kernel if that would work better (not sure if it makes a difference, I dont build recoveries.) but here is a link

https://github.com/thunderc/GingerKernel-thunderc It is not precompiled.

**Comment by koush** [comment]
@sellers86 I'm using the kernel/recovery you linked in the mediafire link above. I assumed that would work on both, since you provided it to me.

**Comment by sellers86** [comment]
it should, BobZhome built that for the new and old screens. all of our current kernels include both screen drivers, so It must be something else... when Im done testing something Ill flash the recovery I linked and see if it works.

**Comment by koush** [comment]
No response on a fix, you guys win. I'll just remove it :)

**Comment by rukin5197** [comment]
All honesty you would get a faster response if you posted the test builds
in the threads. There's only about 3 people that own a vm670 that monitor
this.

**Comment by koush** [comment]
@rukin5197 I know. I've got a lot on my plate. RM currently supports ~200 devices. I've got to maintain the builder, cyanogenmod, and CWM. Keeping track of threads across various forums is not conducive to getting work done. I have to prioritize how I work for the communities that are willing to help out.

**Comment by sellers86** [comment]
what do you mean no response on a fix?

**Pull request closed without merging**
