### PR TITLE
Added ReVolt ROM for the S2 & the S3

### PR DESCRIPTION
**Pull request by johnhany97**

### CODE REVIEW

**Comment by koush** [comment]
Use http://developer.clockworkmod.com to add your ROM please!

**Comment by johnhany97** [comment]
Ok

**Comment by johnhany97** [comment]
It appears on the Website but NOT on the app itself .... What should I do ?

**Comment by koush** [comment]
@johnhany97 Can you point me to where it shows up on the website and I'd be happy to look into it further. Or provide me your developerid as you entered in in the developer portal.

**Comment by johnhany97** [comment]
My developer id is johnhany97
My rom is at tge Samsung galaxy s2 roms at the website and is named ReVolt ROM

**Comment by koush** [comment]
@johnhany97 Have you flashed ROM Manager with the correct recovery?

On your S2, flash the S2 recovery (or use manual flash override).

Then it should show up in the download section.

I just confirmed it shows up on my end.

**Pull request closed without merging**
