### PR TITLE
Hey Koush

### PR DESCRIPTION
**Pull request by hamsterkacke**
I have choosen the awesome way. Pulled your files and edited it. ;)

Hope it's the right way i did this!

### CODE REVIEW

**Comment by koush** [comment]
Hi Hamster. I know that hosting your manifest as a blob on github is problematic. Can you try hosting it on dropbox or using github pages? (You need a paid account to use github pages)
Any web host works really. Also, I would prefer it if you submitted with an icon.

**Comment by koush** [comment]
You can always fix up the hosting for now, and then submit another request for an icon later.

**Comment by DrMacinyasha** [comment]
gh-pages is free. I'm using it for all of my manifests. :P

**Comment by koush** [comment]
nevermind, it works

**Comment by hamsterkacke** [comment]
What is working?

**Comment by koush** [comment]
your ROM is now listed :)

**Pull request merged**
