### PR TITLE
rcteam changes

### PR DESCRIPTION
**Pull request by capychimp**

### CODE REVIEW

**Comment by koush** [comment]
Hi, mind switching to use the developer portal? I am no longer taking change requests on this manifest. The developer portal is much easier to use.

http://developer.clockworkmod.com 

Just put in the same information/manifest url and you'll be good to go in 5 minutes. Let me know here once you're done.

**Comment by capychimp** [comment]
on donate link i type the full link or just email?
and description is description of?

2011/10/27 Koushik Dutta <
reply@reply.github.com>

**Comment by koush** [comment]
Description is what you currently have in the "summary" section of your manifest

"TeamRC RCMixHD Beamingly Blazing HTC Sense Roms"

Use a donation link, full url.

**Comment by capychimp** [comment]
ok tried now

2011/10/27 Poul Meyer capyphone@gmail.com

**Comment by capychimp** [comment]
so for more device supports where do i type that in? thats why i did the
pull request for adding pyramid

2011/10/27 Koushik Dutta <
reply@reply.github.com>

**Comment by capychimp** [comment]
another not how do it work if i use auto management?

2011/10/27 Poul Meyer capyphone@gmail.com

**Comment by koush** [comment]
Provide a manual manifest url.

**Comment by koush** [comment]
You dont need to list the device support anymore. The developer portal will look at your manifest and figure it out automatically.

**Comment by capychimp** [comment]
the one you normally host? i host that myself too with the old js file too?
2011/10/27 Koushik Dutta <
reply@reply.github.com>

**Comment by koush** [comment]
In the manual manifest url, put:

http://capychimp.dk/rcmix/rcmix.js

**Comment by koush** [comment]
Looks like you did it. closing this request.

**Comment by capychimp** [comment]
you dev page wont let me update icon and webpage, nothing happens when i
press update now

2011/10/27 Koushik Dutta <
reply@reply.github.com>

**Comment by koush** [comment]
What browser?

**Comment by capychimp** [comment]
Was ie 9
Den 27/10/2011 18.20 skrev "Koushik Dutta" <
reply@reply.github.com>:

**Pull request closed without merging**
