### PR TITLE
update for Droid Concepts

### PR DESCRIPTION
**Pull request by Woodyman**
I do not know where you are getting your current manifest, forkup was handling this for me, but he has transfered it over to me, so wherever you have that out now you can delete from the RomMananger app, and you can add this one instead.. I have forked your latest update of the ROMManangerManifest repo @ 4:50 pm on sat. April 9th, 2011. And i added my new DroidConcepts.js file. if you have any questions or anything just let me know.. Thanks..

### CODE REVIEW

**Comment by DrMacinyasha** [comment]
Changes merged and are live.

Just one thing that I found odd and wanted to point out: You can put screenshots in each item's listing in your manifest (see the sample manifests for examples), and there's the homepage URL, too. Having an extra entry for "info and screenshots" isn't entirely necessary.

**Comment by Woodyman** [comment]
Thank You. Yes I will add screenshots and what not, I just havn't had the time, Forkup always handled it for me, and I am doing it now, so I will begin to modify it and what not, I will update this either tonight or tomorrow depending on when time permits. :) Thanks..

**Comment by DrMacinyasha** [comment]
If you'd like help updating it, feel free to ping me. I've been trying to get all of the developers to update their manifests to proper JSON code.

**Comment by Woodyman** [comment]
Will do man, thanks.

**Pull request closed without merging**
