### PR TITLE
galaxys2: cwm-flashable radio images

### PR DESCRIPTION
**Pull request by codeworkx**

### CODE REVIEW

**Comment by koush** [comment]
edit manual_manifests.js please. manifest.js is autogenerated.

**Comment by koush** [comment]
Err, I take that back. Can you use http://romshare.deployfu.com?

That let's you set up a manual manifest there too. It's easier for me to maintain :) I'm eventually gonna get everythjing off this manifests.js file.

**Comment by koush** [comment]
Got this working I assume?

**Comment by codeworkx** [comment]
used deployfu to host the radios on my dev account.

**Pull request closed without merging**
